
import React from 'react';

interface SqlQueryDisplayProps {
  sql: string;
}

const SqlQueryDisplay = ({ sql }: SqlQueryDisplayProps) => {
  if (!sql) {
    return null;
  }

  return (
    <div>
      <h3 className="text-lg font-semibold text-slate-800 mb-1">Generated SQL Query</h3>
      <p className="text-sm text-slate-600 mb-4">
        View the SQL query generated by Gemini AI
      </p>
      
      <div className="municipal-card">
        <div className="municipal-card-body">
          <div className="bg-slate-900 rounded-lg p-4 overflow-x-auto border border-green-200">
            <pre className="text-sm text-green-400 font-mono leading-relaxed whitespace-pre-wrap">
              <code>{sql}</code>
            </pre>
          </div>
          <div className="mt-3 text-xs text-slate-600 bg-green-50 p-3 rounded-lg border border-green-200">
            <strong className="text-green-800">Note:</strong> This SQL query was automatically generated by Gemini AI from your natural language prompt.
          </div>
        </div>
      </div>
    </div>
  );
};

export default SqlQueryDisplay;
